import React from "react"
import "./index.css"
export default function PrivacyPolicy(){
    return(
        <div className="static-container">
            <div className="child-static-container">
                <h1>Shipping Policy </h1>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores architecto quia, repellat quis consectetur eveniet sint nam harum cupiditate inventore corrupti doloremque consequatur saepe excepturi ea, beatae expedita suscipit praesentium reprehenderit non fugiat? Cum quod saepe, molestiae animi ut fugit doloremque tempore dolore nostrum ad ipsa et repudiandae porro in fugiat, est eligendi minus obcaecati doloribus? Amet porro accusamus voluptate in doloribus magnam placeat illum architecto hic quos aperiam esse nobis provident, velit, mollitia molestiae doloremque corrupti, laborum repudiandae itaque dicta quo rerum suscipit! Reiciendis optio cupiditate alias voluptate non accusamus iusto eaque consequuntur, dolorum vel rerum voluptatibus aspernatur porro mollitia explicabo possimus facilis provident officia at, exercitationem unde voluptates nulla aliquam. Rem ut iste praesentium optio, modi voluptates quidem voluptatum, illo, quasi nobis ullam nulla. Labore itaque facere repellendus esse illo, voluptas facilis magni fugiat hic adipisci, suscipit provident quia qui? Repellat reiciendis quia, beatae laudantium vel itaque magni tempore, dolore voluptas illum labore aspernatur error cumque eius atque molestiae cupiditate laborum tempora corrupti eligendi nihil vitae, tenetur dolores perspiciatis? Eligendi praesentium sit accusantium provident repudiandae iente ullam? Tenetur eius ipsam consectetur? Quam optio asperiores sit nemo exercitationem, ut et totam molestiae.</p>
                <h1>Shipping Policy </h1>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Asperiores architecto quia, repellat quis consectetur eveniet sint nam harum cupiditate inventore corrupti doloremque consequatur saepe excepturi ea, beatae expedita suscipit praesentium reprehenderit non fugiat? Cum quod saepe, molestiae animi ut fugit doloremque tempore dolore nostrum ad ipsa et repudiandae porro in fugiat, est eligendi minus obcaecati doloribus? Amet porro accusamus voluptate in doloribus magnam placeat illum architecto hic quos aperiam esse nobis provident, velit, mollitia molestiae doloremque corrupti, laborum repudiandae itaque dicta quo rerum suscipit! Reiciendis optio cupiditate alias voluptate non accusamus iusto eaque consequuntur, dolorum vel rerum voluptatibus aspernatur porro mollitia explicabo possimus facilis provident officia at, exercitationem unde voluptates nulla aliquam. Rem ut iste praesentium optio, modi voluptates quidem voluptatum, illo, quasi nobis ullam nulla. Labore itaque facere repellendus esse illo, voluptas facilis magni fugiat hic adipisci, suscipit provident quia qui? Repellat reiciendis quia, beatae laudantium vel itaque magni tempore, dolore voluptas illum labore aspernatur error cumque eius atque molestiae cupiditate laborum tempora corrupti eligendi nihil vitae, tenetur dolores perspiciatis? Eligendi praesentium sit accusantium provident repudiandae iente ullam? Tenetur eius ipsam consectetur? Quam optio asperiores sit nemo exercitationem, ut et totam molestiae.</p>
            </div>
        </div>
    )

}